
export const GETRECONCILATION='GETRECONCILATION';
export const GETFAILUREHANDLER='GETFAILUREHANDLER';
export const ONTEXTCHANGED='ONTEXTCHANGED';
export const ONDELETESTOCK='ONDELETESTOCK';
export const ONSUBMITSTOCK='ONSUBMITSTOCK';
export const ADDITEMS='ADDITEMS';
export const SUBMITFAIL='SUBMITFAIL';

export const ERROR_HANDLING='ERROR_HANDLING';
